### ISSUE TITLE
Actions needed to have the next release as Nov 30

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMArchive#258]
@vkuznet , @ticoann , @amaltaro 

Action #1,  Seangchan will talk with Jen on exitCode and finalized it this week.
Action #2, Seangchan will check the unit issue and make final decision.
Action #3, Valentin check the files with workflow names for the data that Alan upload to WMArchive prod DB that is connected to cmsweb-testbed UI. The date of the uploading is Nov. 16 . Alan tired to fetch them using the UI for time period of Nov 16-23, but was unable to find it. Valentin will try again, if not find it, Alan will rerun the tests. If we could not find the files after rerunning the test, Valentin will check the cron jobs that handling the data.

Action #1 and #2 may involve schema changes, so we need to settle down them ASAP.

**Comment by vkuznet** [comment]
I already checked Alan's workflow and it is not presented in WMArchive. I
posted reply to  https://github.com/dmwm/WMArchive/issues/244 and asked Alan to
generate a new one.

**Comment by vkuznet** [comment]
Hi all,
I verified action #3, Alan's failed files can be seen in WMArchive web UI.
The code now is ready to move forward with production upgrade.

Please reply with action #1, 2 status.

Best,
Valentin.

**Comment by ticoann** [comment]
action 1. Jen hasn't give me the specific a case yet but since Valentin already changed the code to have the same logic as wmstats to handle exitCode, it is good to go. (no schema change)
action 2 checked the data we have in Dec. The unit seems to be fine except readTotalSecs, instead of changing the unit I change the precision in WMAgent code. so there won't be schema change in Archive. - good to go.

There is one more thing I discuss with Valentin about Campaign and PrepID addition.
Although agent is not updated with the patch we can go ahead of schema change
#285

**Comment by vkuznet** [comment]
ok, it means we have everything in place. I just merged the schema, I'll
redeploy one more time on vocms013 and new release will be ready.

**Comment by vkuznet** [comment]
Closing this issue since we accomplished the upgrade.
